# This is a basic workflow to help you get started with Actions

name: Get overpass data

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Install osmtogeojson (and node)
      - name: Install osmtogeojson
        run: |
         sudo apt install nodejs
         npm install -g osmtogeojson

      # Download geojson from overpass.osm.ch
      - name: Download overpass data and convert to geojson
        run: curl http://overpass.osm.ch/api/interpreter?data=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Cowner%3Atype%3Dcooperative%20and%20building%3D*%E2%80%9D%0A*%2F%0A%5Bout%3Ajson%5D%5Btimeout%3A2500%5D%3B%0A%2F%2F%20gather%20results%0A%28%0A%20%20nwr%5B%22owner%3Atype%22%3D%22cooperative%22%5D%5B%22building%22%5D%2845.92631906688105%2C5.89141845703125%2C47.55243302404593%2C8.15460205078125%29%3B%0A%20%20nwr%5B%22owner%3Atype%22%3D%22cooperative%22%5D%5B%22landuse%22%3D%22residential%22%5D%2845.92631906688105%2C5.89141845703125%2C47.55243302404593%2C8.15460205078125%29%3B%0A%20%20nwr%5B%22operator%3Atype%22%3D%22cooperative%22%5D%5B%22building%22%5D%2845.92631906688105%2C5.89141845703125%2C47.55243302404593%2C8.15460205078125%29%3B%0A%20%20nwr%5B%22operator%3Atype%22%3D%22cooperative%22%5D%5B%22landuse%22%3D%22residential%22%5D%2845.92631906688105%2C5.89141845703125%2C47.55243302404593%2C8.15460205078125%29%3B%0A%29%3B%0A%2F%2F%20print%20results%0Aout%20geom%3B | osmtogeojson > cooperative_habitation_suisse.geojson
        
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
