name: Output update

env:
  root_dir: '../../'
  output_dir: '../../output'
  cache_dir: '../../.cache'
  overpass_server: 'http://overpass.osm.ch'
  cooperative_buildings_filename: 'swiss_housing_cooperative_buildings.geojson'
  cooperative_areas_filename: 'swiss_housing_cooperative_areas.geojson'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Push of this file
  push:
    paths:
      - .github/workflows/**
      - '!.github/workflows/cache/**'
  # Every week, at 20:00 on Sunday
  schedule:
    - cron: '0 4 * * 0'

jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: .github/workflows

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          sudo apt-get install jq

          sudo apt install nodejs
          npm install -g n
          sudo n lts
          (cd ./scripts; npm ci)
          npm install -g osmtogeojson
          npm install -g inject-markdown
          npm install -g ejs

      - name: Download buildings overpass data and convert to geojson
        run: ./scripts/download_geojson_overpass.sh "./query/overpass_query_buildings" "$output_dir/$cooperative_buildings_filename"

      - name: Enhance overpass data with wikidata
        run: |
          node ./scripts/add_wikidata.mjs "$output_dir/$cooperative_buildings_filename"

      - name: Enhance overpass data with nominatim to retrieve addresses of buildings without tags
        run: |
          node ./scripts/add_addresses_with_reverse_geocoding.mjs "$output_dir/$cooperative_buildings_filename" "$cache_dir/nominatim_addresses.json"

      - name: Download areas overpass data and convert to geojson
        run: ./scripts/download_geojson_overpass.sh "./query/overpass_query_areas" "$output_dir/$cooperative_areas_filename"

      - name: Get list of cooperative owners
        run: |
          node ./scripts/aggregate_per_identity.mjs "owner" $output_dir/$cooperative_buildings_filename $output_dir/swiss_housing_cooperative_list_owners.tsv

      - name: Get list of cooperative operators
        run: |
          node ./scripts/aggregate_per_identity.mjs "operator" $output_dir/$cooperative_buildings_filename $output_dir/swiss_housing_cooperative_list_operators.tsv

      - name: Update readme cooperative'list
        run: |
          node ./scripts/aggregate_per_identity.mjs "owner" $output_dir/$cooperative_buildings_filename $output_dir/swiss_housing_cooperative_list_owners.json
          ejs ./templates/cooperative_list.ejs -f $output_dir/swiss_housing_cooperative_list_owners.json -o "$root_dir/list_cooperative.html"
          npx inject-markdown "$root_dir/README.md"
          npx inject-markdown "$root_dir/README.fr.md"
          rm -rf "$root_dir/list_cooperative.html"

      # Commit all changed files back to the repository
      - name: Set commit_message variable
        run: |
          if [${{ github.event_name == 'schedule'}}]; then
            echo "COMMIT_MSG=Weekly update" >> $GITHUB_ENV
          elif [${{ github.event_name == 'push'}}]; then
            echo "COMMIT_MSG=Scripts update" >> $GITHUB_ENV
          else
            echo "COMMIT_MSG=Manual workflow update" >> $GITHUB_ENV
          fi

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MSG }}
