# This is a basic workflow to help you get started with Actions

name: Main pipeline

env:
  cooperative_geo_filename: 'cooperative_habitation_suisse.geojson'

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Every week, at 6 am on Sunday
  schedule:
    - cron: '0 6 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies
        run: |
          sudo apt-get install jq
          sudo apt install nodejs
          npm install -g osmtogeojson

      - name: Download overpass data and convert to geojson
        run: |
          curl -d "$(<scripts/overpass_query)" -X POST http://overpass.osm.ch/api/interpreter \
          | osmtogeojson > $cooperative_geo_filename

      - name: Get list of cooperative owners
        run: |
          jq -rf scripts/list_owners.jq $cooperative_geo_filename > list_owner.geojson

      - name: Convert list of cooperative owners to CSV
        run: |
          cat list_owners.geojson \
          | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' \
          > list_owners.csv

      - name: Get list of cooperative operators
        run: |
          jq -rf scripts/list_operators.jq $cooperative_geo_filename > list_operators.geojson

      - name: Convert list of cooperative operator to CSV
        run: |
          cat list_operators.geojson \
          | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' \
          > list_operators.csv

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Weekly geojson update'
